# Generated by Django 5.2 on 2025-04-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="invite_code",
            field=models.CharField(default="52e5efd899", max_length=10, unique=True),
        ),
    ]
