# Generated by Django 5.2 on 2025-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organization_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(default='48120d0ec4', max_length=10, unique=True),
        ),
    ]
