# Generated by Django 5.2 on 2025-04-20 07:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organization_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(default=accounts.models.generate_invite_code, max_length=10, unique=True),
        ),
    ]
